"""Port for the persistent store of tasks, deadlines and notes."""
from datetime import date
from typing import Protocol

from app.domain.entities.deadline import Deadline
from app.domain.entities.note import Note
from app.domain.entities.task import Task


class MemoryStore(Protocol):
    """Persists and queries the user's personal matters."""

    def add_task(self, title: str) -> Task: ...

    def pending_tasks(self) -> list[Task]: ...

    def complete_task(self, task_id: str) -> bool: ...

    def delete_task(self, task_id: str) -> bool: ...

    def complete_deadline(self, deadline_id: str) -> bool: ...

    def delete_deadline(self, deadline_id: str) -> bool: ...

    def reschedule_deadline(self, deadline_id: str, due_date: str, due_time: str = "") -> bool: ...

    def add_deadline(self, title: str, due_date: str, due_time: str = "") -> Deadline: ...

    def deadlines_due_on(self, when: date) -> list[Deadline]: ...

    def upcoming_deadlines(self, limit: int = 10) -> list[Deadline]: ...

    def deadlines_due_within(self, minutes: int = 10) -> list[Deadline]: ...

    def deadline_notified(self, deadline_id: str) -> bool: ...

    def mark_deadline_notified(self, deadline_id: str) -> None: ...

    def add_note(self, text: str) -> Note: ...

    def notes(self, limit: int = 20) -> list[Note]: ...

    def briefing_done_today(self) -> bool: ...

    def mark_briefing_done(self) -> None: ...

    def get_last_seen_email_id(self) -> str | None: ...

    def set_last_seen_email_id(self, email_id: str) -> None: ...
